name: build

on:
  push:
    branches:
      - "develop"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Deploy
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_GITHUB_TOKEN }}
        run: |
          mvn --batch-mode deploy

      - name: Raise Release PR
        run: |
          PAYLOAD=$(cat <<EOF
            {
              "title": "Release",
              "body": "Approve this PR to trigger a release build.",
              "head": "${BRANCH_NAME}",
              "base": "main"
            }
          EOF
          )
          curl https://api.github.com/repos/my-user/other-repo/pulls \
            --header "Authorization: token ${ TOKEN }" \
            -H "Content-Type:application/json" \
            -d "$PAYLOAD"
        env:
          TOKEN: ${{ secrets.PR_GITHUB_TOKEN }}