name: build

on:
  push:
    branches:
      - "develop"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Deploy
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_GITHUB_TOKEN }}
        run: |
          mvn --batch-mode deploy

      - name: Raise Release PR
        uses: peter-evans/create-pull-request@v6
        with:
          title: Release
          branch: main
