name: build

on:
  push:
    branches:
      - "develop"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Deploy
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_GITHUB_TOKEN }}
        run: |
          mvn --batch-mode deploy

      - name: Raise Release PR
        run: |
          PAYLOAD=$(cat <<EOF
            {
              "title": "Release",
              "body": "Approve this PR to trigger a release build.",
              "head": "${BRANCH}",
              "base": "main"
            }
          EOF
          )
          curl -L \
            -X POST \
            -H "Authorization: token ${TOKEN}" \
            -H "Content-Type:application/json" \
            https://api.github.com/repos/${REPOSITORY}/pulls \
            -d "$PAYLOAD"
        env:
          BRANCH: ${{ github.ref }}
          REPOSITORY: ${{ github.repository }}
          TOKEN: ${{ secrets.PR_GITHUB_TOKEN }}